redis:
  host: 127.0.0.1:6379
  pwd: "cmdb_redis"
  sentinelPwd: ""
  database: "0"
  maxOpenConns: 3000
  maxIDleConns: 1000
  snap:
    host: 127.0.0.1:6379
    pwd: "cmdb_redis"
    sentinelPwd: ""
    database: "0"
    enable: "false"
  discover:
    host: 127.0.0.1:6379
    pwd: "cmdb_redis"
    sentinelPwd: ""
    database: "0"
    enable: "false"
  netcollect:
    host: 127.0.0.1:6379
    pwd: "cmdb_redis"
    sentinelPwd: ""
    database: "0"
    enable: "false"
